# Generated by Django 4.1.5 on 2023-01-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('objectType', models.CharField(max_length=10)),
                ('clasification', models.CharField(max_length=50)),
                ('creatorEmail', models.EmailField(max_length=50)),
            ],
        ),
    ]
