# Generated by Django 4.1.5 on 2023-01-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTest', '0003_rename_pelicula_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='puntuation',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
